name: GitHub Actions Demo
on:
  push:
    branches: 
      - main
    paths-ignore: 
      - '.github/**'
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: promt event name
        run: | 
          echo "Name of event ${{ github.event_name }}"
          echo "Name of the branch ${{github.ref}}"
      - uses: actions/checkout@v3.3.0

      - name: List files
        run: |
          echo "List files  ${{ github.repository }} "
          tree
          ###find . -type f
          
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - name: Env test manual execute
        run:
          echo "Testing ... :alien"
    

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Production
    environment: Load-Test
    steps:
      - name: Env Load-Test manual execute
        run:
          echo ":rocket Testing ..."
    
  Production:
    runs-on: ubuntu-latest
    needs: [Test,Load-Test]
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - name: Env Production manual execute
        run: |
          echo ":rocket Step 1 ..."
          sleep 10
          echo ":rocket Step 2 ..."
          sleep 10
          echo ":rocket Step 3 ..."
          sleep 10
          echo ":rocket Step 4 ..."
          sleep 10
          echo ":rocket Step 5 ..."



    
      
      
    
