name: GitHub Actions Demo
on:
  push:
    branches: 
      - main
    paths-ignore: 
      - '.github/**'
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: promt event name
        run: | 
          echo "Name of event ${{ github.event_name }}"
          echo "Name of the branch ${{github.ref}}"
      - uses: actions/checkout@v3.3.0

      - name: List files
        run: |
          echo "List files  ${{ github.repository }} "
          tree  #find . -type f



    
      
      
    
